"""
Django settings for journey_begins project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
from firebase_admin import firestore
from firebase_admin import credentials
import firebase_admin
import os
from pathlib import Path

from Tools.scripts.var_access_benchmark import B

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$!yaq=9-=-ws@!tdlqsxy#i502)t)%9-%s%()srvl@6d2d)9e('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
json_firebase={
  "type": "service_account",
  "project_id": "sece-hackathon-390a0",
  "private_key_id": "d1b100b940c4d861831a5075c7d5d4d48e7bd9b5",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCsSlnEazKpFmFl\n6JxQ7efczwqCJAjoq7pdl2K0j73pctV6H35wIVqbM/jm7aTMFJUahsYuNTEg42ec\n6fe+f6He/7vzwolHj5QXYu+otsaZirYaVb3REG1IAiLSoX9vYOR59nG2AkSom6oC\no7RbSeiL+h895GFiNxPavglt5siR49ISsx7fmuQ9vEpexUsY/SBqJOqNQdf9CRNP\ny4Tm8T6wTSvQlS595XVW0g58uigCI48ORqItvFuRgvDzQeUwJhYTFe4cI0HwxXJw\nNyorUsA6IBbMhSXK22Mr/Awf3+WZem8JwrMdEB38WB4il+8X0Qyr+wB708XCbgLT\nOjL0NKmJAgMBAAECggEAExDXwfoUZTyIKvc8rCKFouxo9umesEPHuAFvj3hsLVQz\nPkRTsTwpqwzrbX+tGdXpwaGaNwUVIpTzs3w7OaIlYzh038beevQvMM7Wo1qVm+pr\nGDs2ihcJptswqBMt12EXK417fCcgWrG+NLRRujvxr2LOmAJoye37JRzcTYSJW8Z1\nxzNOm9Nhv0o5Jlm98roK3Y3t3+4DRdE7CQFV/465GMtGi9XwP+3/dzOLV02pFTXO\nlDwAyXyEXadnftvJG1a0+JeVgiHXDlQ4rAMmdWSwidJF9iw4IysQ+mMy6KwgDFAU\nkE/acIVl5AMIfyo7Q4RZXxmCAI2LtF2MlpWt7x4lUQKBgQDvmJutSHTKkaMTsEYL\naNvL0Lw5JX6FIVQz1lJjA63nUBp5YARuKwRVdk0emDinqG5Rl0cJlgmsDLuoEYj0\nVuNLkT//wKdpS6QXziRVpMus3y3Z/S/5IdlCTQEUo1aMXXuARK+yGiCcAKY71w+m\nydw95OMiMb4BER4cpQgTsoxNeQKBgQC4FhQLS1YRmbV4XrwF0jhnXtDZVU5BxnO/\nW4bWRc83UumctHjVVMf8lZ6MnIAugqZNi9/vzG/W4AwShEkTZtwWTh76dizNHlGh\nJt1yOudR9Q78uzS91/h28J1aTRbfCn5bWSfSRF88ZRK/eGA1JWqC00sQy57818dg\n2iu7e5kIkQKBgQCA5y7iRHgpP79n6U9V9h1Cg1Owvx5Zi7vcg7MheCpIp40GvgTE\nLLqRLCuDiUv5z6FCnkvmuWUMvnD7lCuFoXV6A3RWKZUoDj0DXbGorheyMwRdIl18\nAJz9kaZCLzpyHB1Evi90d6ARrjvBOAxApJusZQdaLz7VHhuAN72ns0jOqQKBgFLq\nZubbbQ4KbOmlygzZLlypIWry+Ie56oLDqA01bmtd5imWRGLaiCWmAr8U8suAP4Xo\nPdqV+74ONoHUodGiX/mQAHYR6oYNZPkwN0hvbafFuJVvgQcNkzWHlWiKFoYqBNYC\nZ2RXNYpPgE1L3BG0I7B/mW0cOiVqz7w5KL+OoVRxAoGAPMRfcgZxZoZ+nG/WmTtD\ntmi2F5fFLtoVYgpAYRVd3cgOZC4+srRakrA7YCXSsIUGk6d6K7e47aPpXNgdhcN3\n+X7+RIbRT5SkkfvP4qXZs+5GbHmheorqqoeaJXC6exUlyLehEcWecMlU6iZKA+ib\nb9sduzDFETb2EFo4eAZgMuQ=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-2xz8a@sece-hackathon-390a0.iam.gserviceaccount.com",
  "client_id": "111911728803949010269",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-2xz8a%40sece-hackathon-390a0.iam.gserviceaccount.com"
}
cred=credentials.Certificate(json_firebase)
firebase_admin.initialize_app(cred)
fire=firestore.client()
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Home_Page',
    'Bus',
    'Payment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'journey_begins.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'journey_begins.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#STATIC_ROOT=os.path.join(BASE_DIR,'Home_Page/static')
#print(BASE_DIR)
STATICFILES_DIRS=(os.path.join(BASE_DIR,'static'),)
